### ISSUE TITLE
Webhooks instead of ExternalEventPooler

### ISSUE THREAD

**Issue by homesweethole** [bemoty/genius-discord-bot#2]
Replace flag files with [Discord Webhooks.](https://support.discordapp.com/hc/de/articles/228383668-Webhooks-verwenden)

**Comment by bemoty** [comment]
adding a webhook to a discord server creates a NEW "virtual" bot; you can't attach a webhook to an already existing bot (like ours) or something like that, so i don't think this is going to work.
